from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any

from .common import *  # noqa: F403
from .compiler import compile_catalog

ROOT = Path(__file__).resolve().parents[4]


def typescript_summary(summary: dict[str, Any], datasets: dict[str, list[dict[str, Any]]], manifest: dict[str, Any]) -> str:
    repositories = sorted(
        datasets["repositories"],
        key=lambda item: (-item["metrics"]["stars"], -item["metrics"]["commits"], item["full_name"]),
    )[:12]
    featured = [{key: item[key] for key in ("id", "route", "display_name", "description", "owner", "metrics", "technologies", "observed_at")} for item in repositories]
    technologies = sorted(datasets["technologies"], key=lambda item: (-item["repository_count"], -item["bytes"], item["name"]))
    values = {
        "catalogSummary": summary,
        "catalogOrganizations": datasets["organizations"],
        "catalogFeaturedRepositories": featured,
        "catalogTechnologies": technologies,
        "catalogDatasetManifest": manifest,
    }
    lines = ["// Generated by scripts/catalog_render.py. Do not edit manually."]
    for name, value in values.items():
        lines.append(f"export const {name} = {json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False)} as const;")
    return "\n\n".join(lines) + "\n"


def write_product_evidence(
    directory: Path,
    catalog: dict[str, Any],
    datasets: dict[str, list[dict[str, Any]]],
    attachments_path: Path | None = None,
) -> int:
    """Emit small repository-scoped joins for product pages without loading the full package catalog."""
    if directory.exists():
        shutil.rmtree(directory)
    repositories = {record["full_name"]: record for record in datasets["repositories"]}
    packages_by_repository: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for package in datasets["packages"]:
        if package.get("repository"):
            packages_by_repository[str(package["repository"])].append(package)
    for full_name, repository in repositories.items():
        owner, name = full_name.split("/", 1)
        bundle = {
            "schema_version": "1.0.0",
            "generated_at": catalog["generated_at"],
            "repository": repository,
            "packages": sorted(packages_by_repository.get(full_name, []), key=lambda item: (item.get("ecosystem", ""), item.get("name", ""))),
        }
        write_json(directory / owner / f"{name}.json", bundle)

    if attachments_path and attachments_path.exists():
        attachments = json.loads(attachments_path.read_text(encoding="utf-8"))
        for record_key, attachment in attachments.get("records", {}).items():
            repository_names = attachment.get("repositories", [])
            attached_repositories = [repositories[name] for name in repository_names if name in repositories]
            if not attached_repositories:
                continue
            primary_name = attachment.get("primary_repository")
            primary = repositories.get(primary_name, attached_repositories[0])
            resource_terms = [
                str(term).lower() for term in attachment.get("resource_contains", []) if str(term)
            ]
            merged_repository = dict(primary)
            merged_repository["attached_repositories"] = [
                {
                    "id": repository["id"],
                    "full_name": repository["full_name"],
                    "route": repository["route"],
                    "source_url": repository.get("source_url") or repository.get("url"),
                    "description": repository["description"],
                    "default_branch": repository.get("default_branch"),
                    "archived": repository.get("archived", False),
                    "fork": repository.get("fork", False),
                    "metrics": repository.get("metrics", {}),
                    "latest_release": repository.get("latest_release"),
                    "github_releases": repository.get("github_releases", []),
                    "latest_deployment": repository.get("latest_deployment"),
                    "ssot_governance": repository.get("ssot_governance", {}),
                    "attachment_role": attachment.get("repository_roles", {}).get(
                        repository["full_name"], "implementation"
                    ),
                }
                for repository in attached_repositories
            ]
            merged_repository["related_resources"] = sorted(
                ({
                    resource["id"]: resource
                    for repository in attached_repositories
                    for resource in repository.get("related_resources", [])
                    if not resource_terms
                    or any(
                        term
                        in " ".join(
                            str(resource.get(field, "")).lower()
                            for field in ("name", "url", "kind")
                        )
                        for term in resource_terms
                    )
                } | {
                    resource.get("id")
                    or f"resource:{stable_hash(str(resource.get('url') or resource.get('name')))}": {
                        "id": resource.get("id")
                        or f"resource:{stable_hash(str(resource.get('url') or resource.get('name')))}",
                        **resource,
                    }
                    for resource in attachment.get("resources", [])
                }).values(),
                key=lambda item: (item.get("kind", ""), item.get("name", "")),
            )
            merged_packages = sorted(
                {
                    package["id"]: {
                        **package,
                        "attachment_role": attachment.get("package_roles", {}).get(
                            str(package.get("repository")), "distribution"
                        ),
                    }
                    for repository_name in attachment.get("package_repositories", repository_names)
                    for package in packages_by_repository.get(repository_name, [])
                }.values(),
                key=lambda item: (item.get("ecosystem", ""), item.get("name", "")),
            )
            owner, name = record_key.split("/", 1)
            write_json(
                directory / owner / f"{name}.json",
                {
                    "schema_version": "1.0.0",
                    "generated_at": catalog["generated_at"],
                    "repository": merged_repository,
                    "packages": merged_packages,
                },
            )
    return len(list(directory.glob("*/*.json")))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=ROOT / "catalog" / "generated" / "catalog.json")
    parser.add_argument("--summary", type=Path, default=ROOT / "catalog" / "generated" / "summary.json")
    parser.add_argument("--site-dir", type=Path, default=ROOT / "catalog" / "generated" / "site")
    parser.add_argument("--product-evidence-dir", type=Path, default=ROOT / "catalog" / "generated" / "product-evidence")
    parser.add_argument("--editorial", type=Path, default=ROOT / "catalog" / "content" / "editorial.json")
    parser.add_argument(
        "--record-attachments",
        type=Path,
        default=ROOT / "catalog" / "content" / "record-attachments.json",
    )
    parser.add_argument(
        "--typescript",
        type=Path,
        default=ROOT / "pkgs" / "frontend" / "src" / "data" / "catalog.generated.ts",
    )
    args = parser.parse_args()
    catalog = repair_text(json.loads(args.catalog.read_text(encoding="utf-8")))
    editorial = load_editorial(args.editorial)
    summary = summarize(catalog)
    datasets = compile_catalog(catalog, editorial)
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.typescript.parent.mkdir(parents=True, exist_ok=True)
    args.site_dir.mkdir(parents=True, exist_ok=True)
    for stale_name in ("releases", "deployments", "relationships", "surfaces"):
        (args.site_dir / f"{stale_name}.json").unlink(missing_ok=True)
    write_json(args.summary, summary)
    files = []
    for name, records in datasets.items():
        files.append({"dataset": name, **write_json(args.site_dir / f"{name}.json", records)})
    product_evidence_count = write_product_evidence(
        args.product_evidence_dir,
        catalog,
        datasets,
        args.record_attachments,
    )
    manifest = {
        "schema_version": "1.0.0",
        "generated_at": catalog["generated_at"],
        "source": "/catalog/catalog.json",
        "files": sorted(files, key=lambda item: item["dataset"]),
        "counts": {name: len(records) for name, records in sorted(datasets.items())},
        "source_counts": {
            "releases": summary["github_releases"] + summary["registry_release_versions"] + summary["github_package_versions"],
            "deployments": summary["deployments"],
            "relationships": summary["relationships"],
        },
        "product_evidence": {"path": "/catalog/product-evidence/", "records": product_evidence_count},
        "completeness": catalog.get("completeness", {}),
    }
    write_json(args.site_dir / "manifest.json", manifest)
    args.typescript.write_text(typescript_summary(summary, datasets, manifest), encoding="utf-8")
    print(json.dumps({"generated_at": catalog["generated_at"], "counts": manifest["counts"]}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
