from .activity import RESOURCE_TABLES as ACTIVITY_TABLES
from .artifact import RESOURCE_TABLES as ARTIFACT_TABLES
from .asset import RESOURCE_TABLES as ASSET_TABLES
from .automation import RESOURCE_TABLES as AUTOMATION_TABLES
from .collection import RESOURCE_TABLES as COLLECTION_TABLES
from .content import RESOURCE_TABLES as CONTENT_TABLES
from .contract import RESOURCE_TABLES as CONTRACT_TABLES
from .data import RESOURCE_TABLES as DATA_TABLES
from .distribution import RESOURCE_TABLES as DISTRIBUTION_TABLES
from .documentation import RESOURCE_TABLES as DOCUMENTATION_TABLES
from .governance import RESOURCE_TABLES as GOVERNANCE_TABLES
from .implementation import RESOURCE_TABLES as IMPLEMENTATION_TABLES
from .interface import RESOURCE_TABLES as INTERFACE_TABLES
from .legal import RESOURCE_TABLES as LEGAL_TABLES
from .offering import RESOURCE_TABLES as OFFERING_TABLES
from .party import RESOURCE_TABLES as PARTY_TABLES
from .release import RESOURCE_TABLES as RELEASE_TABLES
from .runtime import RESOURCE_TABLES as RUNTIME_TABLES
from .source import RESOURCE_TABLES as SOURCE_TABLES
from .taxonomy import RESOURCE_TABLES as TAXONOMY_TABLES
from .work import RESOURCE_TABLES as WORK_TABLES

RESOURCE_TABLES = {
    **ACTIVITY_TABLES,
    **ARTIFACT_TABLES,
    **ASSET_TABLES,
    **AUTOMATION_TABLES,
    **COLLECTION_TABLES,
    **CONTENT_TABLES,
    **CONTRACT_TABLES,
    **DATA_TABLES,
    **DISTRIBUTION_TABLES,
    **DOCUMENTATION_TABLES,
    **GOVERNANCE_TABLES,
    **IMPLEMENTATION_TABLES,
    **INTERFACE_TABLES,
    **LEGAL_TABLES,
    **OFFERING_TABLES,
    **PARTY_TABLES,
    **RELEASE_TABLES,
    **RUNTIME_TABLES,
    **SOURCE_TABLES,
    **TAXONOMY_TABLES,
    **WORK_TABLES,
}

RESOURCE_ENTITY_TABLES = tuple(RESOURCE_TABLES.values())

__all__ = ["RESOURCE_ENTITY_TABLES", "RESOURCE_TABLES"]
