from .governance.tables import (
    Claim,
    ClaimEvidence,
    Evidence,
    Feature,
    RepositorySsotInventory,
    RepositorySsotRegistry,
    ResourceEvidence,
)
from .observations.tables import CollectionRun, MetricObservation, Observation
from .organizations.tables import Organization, Person
from .packages.tables import Dependency, Package, PackageRepository, PackageTaxonomy
from .records.tables import (
    Deployment,
    Limitation,
    Record,
    RecordAlias,
    RecordAuthor,
    RecordFeature,
    RecordPackage,
    RecordRelation,
    RecordRepository,
    RecordTaxonomy,
    Taxonomy,
)
from .releases.tables import LegalEvidence, Release
from .repositories.tables import Repository, RepositoryContributor, RepositoryLanguage
from .resources.tables import (
    CatalogEntity,
    EntityAlias,
    EntityRelationship,
    EntityType,
    EntityUrl,
    RecordResource,
    Resource,
    ResourceRepository,
    ResourceTaxonomy,
    ResourceType,
)

ALL_TABLES = (
    Organization,
    Person,
    EntityType,
    CatalogEntity,
    EntityAlias,
    EntityUrl,
    EntityRelationship,
    Resource,
    ResourceType,
    ResourceRepository,
    ResourceTaxonomy,
    RecordResource,
    Record,
    RecordAlias,
    RecordRelation,
    RecordAuthor,
    Taxonomy,
    RecordTaxonomy,
    RecordRepository,
    RecordPackage,
    RecordFeature,
    Limitation,
    Deployment,
    Repository,
    RepositoryContributor,
    RepositoryLanguage,
    Package,
    PackageRepository,
    PackageTaxonomy,
    Dependency,
    Release,
    LegalEvidence,
    Feature,
    Claim,
    Evidence,
    ClaimEvidence,
    ResourceEvidence,
    RepositorySsotRegistry,
    RepositorySsotInventory,
    CollectionRun,
    Observation,
    MetricObservation,
)
