// Generated by scripts/catalog_render.py. Do not edit manually.

export const catalogSummary = {
  "archived_repositories": 0,
  "commits": 23667,
  "contributors_unique": 42,
  "deployments": 4010,
  "environments": 130,
  "fork_repositories": 0,
  "forks": 108,
  "generated_at": "2026-08-03T23:39:08Z",
  "github_package_versions": 27,
  "github_releases": 7534,
  "observations_by_status": {
    "cached": 1425,
    "error": 431,
    "not_found": 515,
    "observed": 4653
  },
  "observations_with_errors": 431,
  "owners": 4,
  "package_ecosystems": {
    "crates": 5,
    "ghcr": 1,
    "npm": 166,
    "pypi": 953
  },
  "packages": 1125,
  "published_packages": 490,
  "registry_release_versions": 9752,
  "relationships": 10734,
  "repositories": 68,
  "schema_version": "1.0.0",
  "stars": 198,
  "verified_languages": [
    "C",
    "C++",
    "CSS",
    "Dockerfile",
    "HTML",
    "JavaScript",
    "Jinja",
    "Jupyter Notebook",
    "MDX",
    "Makefile",
    "Meson",
    "Python",
    "Rust",
    "Shell",
    "Svelte",
    "TypeScript",
    "Vue",
    "XSLT"
  ],
  "watchers": 11
} as const;

export const catalogOrganizations = [
  {
    "commits": 0,
    "contributors": 0,
    "deployments": 0,
    "description": "Public ecosystem inventory for the bucketwarden GitHub organization.",
    "display_name": "Bucketwarden",
    "evidence": [
      {
        "kind": "organization",
        "observed_at": "2026-08-03T23:39:08Z",
        "url": "https://github.com/bucketwarden"
      }
    ],
    "featured_repositories": [],
    "forks": 0,
    "github_releases": 0,
    "id": "organization:bucketwarden",
    "kind": "organization",
    "login": "bucketwarden",
    "observed_at": "2026-08-03T23:39:08Z",
    "package_count": 0,
    "package_releases": 0,
    "relationships": 0,
    "repository_count": 0,
    "role": "product",
    "route": "/catalog",
    "stars": 0,
    "technologies": [],
    "watchers": 0
  },
  {
    "commits": 2199,
    "contributors": 2,
    "deployments": 589,
    "description": "Public source, packages, and delivery records maintained by Groupsum.",
    "display_name": "Groupsum",
    "evidence": [
      {
        "kind": "organization",
        "observed_at": "2026-08-03T23:39:08Z",
        "url": "https://github.com/groupsum"
      }
    ],
    "featured_repositories": [
      {
        "description": "Repository-agnostic Python CLI for single-source-of-truth traceability from features to evidence-backed releases.",
        "id": "repository:groupsum/ssot-registry",
        "metrics": {
          "commits": 485,
          "contributors": 2,
          "deployments": 528,
          "environments": 1,
          "forks": 0,
          "github_releases": 447,
          "open_issues": 0,
          "packages": 14,
          "related_resources": 35,
          "size_kb": 77017,
          "stars": 5,
          "watchers": 0
        },
        "name": "ssot-registry",
        "route": "/catalog/repositories/groupsum/ssot-registry"
      },
      {
        "description": "MdWrk is a local-first Markdown workspace, preview editor, package platform, and extension host for portable Markdown authoring.",
        "id": "repository:groupsum/markdown_workspace",
        "metrics": {
          "commits": 837,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 1,
          "github_releases": 6,
          "open_issues": 0,
          "packages": 45,
          "related_resources": 76,
          "size_kb": 1133214,
          "stars": 3,
          "watchers": 0
        },
        "name": "markdown_workspace",
        "route": "/catalog/repositories/groupsum/markdown_workspace"
      },
      {
        "description": "Installable ADR/SPEC extension pack for SEO, AEO, and AiEO governance, designed for downstream ssot-registry sync.",
        "id": "repository:groupsum/seo-aeo-aieo-governance-pack",
        "metrics": {
          "commits": 30,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 7,
          "open_issues": 0,
          "packages": 1,
          "related_resources": 0,
          "size_kb": 131,
          "stars": 2,
          "watchers": 0
        },
        "name": "seo-aeo-aieo-governance-pack",
        "route": "/catalog/repositories/groupsum/seo-aeo-aieo-governance-pack"
      },
      {
        "description": "Owner-scoped GitOps controller for Nginx Proxy Manager proxy hosts, SSL certificates, and access lists.",
        "id": "repository:groupsum/npmctl",
        "metrics": {
          "commits": 92,
          "contributors": 2,
          "deployments": 6,
          "environments": 1,
          "forks": 0,
          "github_releases": 9,
          "open_issues": 0,
          "packages": 7,
          "related_resources": 39,
          "size_kb": 11109,
          "stars": 1,
          "watchers": 0
        },
        "name": "npmctl",
        "route": "/catalog/repositories/groupsum/npmctl"
      },
      {
        "description": "Installable SSOT ADR/SPEC extension pack for HTTP caching, freshness, validators, stale controls, Cache-Control, ETag, and CDN cache governance.",
        "id": "repository:groupsum/cache-freshness-governance-pack",
        "metrics": {
          "commits": 21,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 6,
          "open_issues": 0,
          "packages": 1,
          "related_resources": 1,
          "size_kb": 75,
          "stars": 1,
          "watchers": 0
        },
        "name": "cache-freshness-governance-pack",
        "route": "/catalog/repositories/groupsum/cache-freshness-governance-pack"
      },
      {
        "description": "Installable SSOT ADR/SPEC extension pack for digital-signature, advanced electronic signature, container, timestamping, validation, archival, and assurance governance.",
        "id": "repository:groupsum/digital-signature-governance-pack",
        "metrics": {
          "commits": 20,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 4,
          "open_issues": 0,
          "packages": 1,
          "related_resources": 2,
          "size_kb": 81,
          "stars": 1,
          "watchers": 0
        },
        "name": "digital-signature-governance-pack",
        "route": "/catalog/repositories/groupsum/digital-signature-governance-pack"
      },
      {
        "description": "A self-hosted, API-compatible reverse proxy control plane and UI for npmctl.",
        "id": "repository:groupsum/portwyrm",
        "metrics": {
          "commits": 95,
          "contributors": 1,
          "deployments": 5,
          "environments": 1,
          "forks": 0,
          "github_releases": 2,
          "open_issues": 0,
          "packages": 3,
          "related_resources": 15,
          "size_kb": 1958,
          "stars": 0,
          "watchers": 0
        },
        "name": "portwyrm",
        "route": "/catalog/repositories/groupsum/portwyrm"
      },
      {
        "description": "MdWrk Pages package suite for typed content, page templates, static-site compilation, SEO/discovery artifacts, and React rendering.",
        "id": "repository:groupsum/mdwrk-pages",
        "metrics": {
          "commits": 82,
          "contributors": 1,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 22,
          "related_resources": 12,
          "size_kb": 15064,
          "stars": 0,
          "watchers": 0
        },
        "name": "mdwrk-pages",
        "route": "/catalog/repositories/groupsum/mdwrk-pages"
      }
    ],
    "forks": 1,
    "github_releases": 505,
    "id": "organization:groupsum",
    "kind": "organization",
    "login": "groupsum",
    "observed_at": "2026-08-03T23:39:08Z",
    "package_count": 152,
    "package_releases": 572,
    "relationships": 1231,
    "repository_count": 37,
    "role": "primary",
    "route": "/products/groupsum",
    "stars": 13,
    "technologies": [
      "CSS",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Makefile",
      "Python",
      "Rust",
      "Shell",
      "TypeScript",
      "XSLT"
    ],
    "watchers": 0
  },
  {
    "commits": 19262,
    "contributors": 40,
    "deployments": 831,
    "description": "Public SDK, package, application, and developer-tooling records maintained by Swarmauri.",
    "display_name": "Swarmauri",
    "evidence": [
      {
        "kind": "organization",
        "observed_at": "2026-08-03T23:39:08Z",
        "url": "https://github.com/swarmauri"
      }
    ],
    "featured_repositories": [
      {
        "description": "Modular Python SDK and monorepo for AI agents, LLM integrations, tools, parsers, embeddings, vector stores, and extensible application workflows.",
        "id": "repository:swarmauri/swarmauri-sdk",
        "metrics": {
          "commits": 17469,
          "contributors": 20,
          "deployments": 802,
          "environments": 91,
          "forks": 51,
          "github_releases": 5742,
          "open_issues": 176,
          "packages": 366,
          "related_resources": 111,
          "size_kb": 77235,
          "stars": 104,
          "watchers": 5
        },
        "name": "swarmauri-sdk",
        "route": "/catalog/repositories/swarmauri/swarmauri-sdk"
      },
      {
        "description": "A UI Component Library by Swarmauri",
        "id": "repository:swarmauri/swarmakit",
        "metrics": {
          "commits": 736,
          "contributors": 6,
          "deployments": 2,
          "environments": 1,
          "forks": 10,
          "github_releases": 3,
          "open_issues": 9,
          "packages": 5,
          "related_resources": 1,
          "size_kb": 3968,
          "stars": 25,
          "watchers": 0
        },
        "name": "swarmakit",
        "route": "/catalog/repositories/swarmauri/swarmakit"
      },
      {
        "description": "Public source repository swarmauri/swarmauri-notebooks.",
        "id": "repository:swarmauri/swarmauri-notebooks",
        "metrics": {
          "commits": 378,
          "contributors": 20,
          "deployments": 0,
          "environments": 0,
          "forks": 31,
          "github_releases": 1,
          "open_issues": 25,
          "packages": 0,
          "related_resources": 1,
          "size_kb": 32789,
          "stars": 18,
          "watchers": 4
        },
        "name": "swarmauri-notebooks",
        "route": "/catalog/repositories/swarmauri/swarmauri-notebooks"
      },
      {
        "description": "A CRUD Router for Fast-Creation of CRUD Routes",
        "id": "repository:swarmauri/crouton",
        "metrics": {
          "commits": 208,
          "contributors": 6,
          "deployments": 0,
          "environments": 0,
          "forks": 6,
          "github_releases": 0,
          "open_issues": 8,
          "packages": 2,
          "related_resources": 1,
          "size_kb": 237,
          "stars": 10,
          "watchers": 0
        },
        "name": "crouton",
        "route": "/catalog/repositories/swarmauri/crouton"
      },
      {
        "description": "A multi-provider, multi-model retrieval augmentation chatbot.",
        "id": "repository:swarmauri/rag_assistant",
        "metrics": {
          "commits": 133,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 2,
          "github_releases": 1,
          "open_issues": 2,
          "packages": 1,
          "related_resources": 1,
          "size_kb": 254,
          "stars": 7,
          "watchers": 0
        },
        "name": "rag_assistant",
        "route": "/catalog/repositories/swarmauri/rag_assistant"
      },
      {
        "description": "An LLM playground by Swarmauri",
        "id": "repository:swarmauri/swarmauri-playground",
        "metrics": {
          "commits": 37,
          "contributors": 4,
          "deployments": 0,
          "environments": 0,
          "forks": 4,
          "github_releases": 0,
          "open_issues": 9,
          "packages": 0,
          "related_resources": 1,
          "size_kb": 34,
          "stars": 5,
          "watchers": 1
        },
        "name": "swarmauri-playground",
        "route": "/catalog/repositories/swarmauri/swarmauri-playground"
      },
      {
        "description": "Swarmauri custom mesop components",
        "id": "repository:swarmauri/swarmauri-mesop-components",
        "metrics": {
          "commits": 11,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 1,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 0,
          "related_resources": 1,
          "size_kb": 17,
          "stars": 3,
          "watchers": 0
        },
        "name": "swarmauri-mesop-components",
        "route": "/catalog/repositories/swarmauri/swarmauri-mesop-components"
      },
      {
        "description": "Soliloquy is a unified command-line tool for managing a Python monorepo that contains multiple standalone packages—each with its own pyproject.toml. It consolidates common tasks such as dependency management, version bumping, remote dependency resolution, test execution and analysis, and project configuration updates into one robust CLI.",
        "id": "repository:swarmauri/soliloquy",
        "metrics": {
          "commits": 89,
          "contributors": 1,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 3,
          "packages": 1,
          "related_resources": 1,
          "size_kb": 149,
          "stars": 2,
          "watchers": 0
        },
        "name": "soliloquy",
        "route": "/catalog/repositories/swarmauri/soliloquy"
      }
    ],
    "forks": 105,
    "github_releases": 5747,
    "id": "organization:swarmauri",
    "kind": "organization",
    "login": "swarmauri",
    "observed_at": "2026-08-03T23:39:08Z",
    "package_count": 389,
    "package_releases": 7372,
    "relationships": 5668,
    "repository_count": 16,
    "role": "ecosystem",
    "route": "/products/swarmauri",
    "stars": 176,
    "technologies": [
      "C",
      "C++",
      "CSS",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Jinja",
      "Jupyter Notebook",
      "MDX",
      "Meson",
      "Python",
      "Rust",
      "Shell",
      "Svelte",
      "TypeScript",
      "Vue",
      "XSLT"
    ],
    "watchers": 10
  },
  {
    "commits": 2206,
    "contributors": 5,
    "deployments": 2590,
    "description": "Public API, ASGI, identity, transport, package, and example records maintained by Tigrbl.",
    "display_name": "Tigrbl",
    "evidence": [
      {
        "kind": "organization",
        "observed_at": "2026-08-03T23:39:08Z",
        "url": "https://github.com/tigrbl"
      }
    ],
    "featured_repositories": [
      {
        "description": "Schema-first Python and Rust workspace for REST and JSON-RPC APIs with typed validation, SQLAlchemy models, and engine-backed execution.",
        "id": "repository:tigrbl/tigrbl",
        "metrics": {
          "commits": 638,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 1202,
          "open_issues": 2,
          "packages": 54,
          "related_resources": 31,
          "size_kb": 73673,
          "stars": 3,
          "watchers": 0
        },
        "name": "tigrbl",
        "route": "/catalog/repositories/tigrbl/tigrbl"
      },
      {
        "description": "ASGI3 server with built-in HTTP/1.1, HTTP/2, HTTP/3, QUIC, WebSocket, TLS, static delivery, and release validation.",
        "id": "repository:tigrbl/tigrcorn",
        "metrics": {
          "commits": 274,
          "contributors": 4,
          "deployments": 2454,
          "environments": 6,
          "forks": 2,
          "github_releases": 40,
          "open_issues": 15,
          "packages": 16,
          "related_resources": 37,
          "size_kb": 18970,
          "stars": 3,
          "watchers": 1
        },
        "name": "tigrcorn",
        "route": "/catalog/repositories/tigrbl/tigrcorn"
      },
      {
        "description": "Tigrbl-native multi-tenant OpenID Connect / OAuth 2.0 identity provider with ASGI runtime profiles, JWKS/JWT support, operator controls, and SSOT-backed compliance evidence.",
        "id": "repository:tigrbl/tigrbl_auth",
        "metrics": {
          "commits": 916,
          "contributors": 2,
          "deployments": 121,
          "environments": 1,
          "forks": 0,
          "github_releases": 12,
          "open_issues": 13,
          "packages": 489,
          "related_resources": 56,
          "size_kb": 25828,
          "stars": 2,
          "watchers": 0
        },
        "name": "tigrbl_auth",
        "route": "/catalog/repositories/tigrbl/tigrbl_auth"
      },
      {
        "description": "A formal ASGI event contract that normalizes HTTP, WebSocket, QUIC, and WebTransport into a typed, capability-safe application IR.",
        "id": "repository:tigrbl/tigr-asgi-contract",
        "metrics": {
          "commits": 185,
          "contributors": 2,
          "deployments": 0,
          "environments": 0,
          "forks": 0,
          "github_releases": 28,
          "open_issues": 0,
          "packages": 8,
          "related_resources": 16,
          "size_kb": 4249,
          "stars": 1,
          "watchers": 0
        },
        "name": "tigr-asgi-contract",
        "route": "/catalog/repositories/tigrbl/tigr-asgi-contract"
      },
      {
        "description": "MdWrk lander website for tigrcorn.com.",
        "id": "repository:tigrbl/tigrcorn-com",
        "metrics": {
          "commits": 50,
          "contributors": 1,
          "deployments": 8,
          "environments": 1,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 3,
          "related_resources": 1,
          "size_kb": 1816,
          "stars": 0,
          "watchers": 0
        },
        "name": "tigrcorn-com",
        "route": "/catalog/repositories/tigrbl/tigrcorn-com"
      },
      {
        "description": "MdWrk lander website for tigrbl.com.",
        "id": "repository:tigrbl/tigrbl-com",
        "metrics": {
          "commits": 47,
          "contributors": 1,
          "deployments": 6,
          "environments": 1,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 3,
          "related_resources": 0,
          "size_kb": 2968,
          "stars": 0,
          "watchers": 0
        },
        "name": "tigrbl-com",
        "route": "/catalog/repositories/tigrbl/tigrbl-com"
      },
      {
        "description": "ZDX and MkDocs Material documentation website for docs.tigrbl.com.",
        "id": "repository:tigrbl/docs-tigrbl-com",
        "metrics": {
          "commits": 35,
          "contributors": 1,
          "deployments": 0,
          "environments": 1,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 2,
          "related_resources": 6,
          "size_kb": 141,
          "stars": 0,
          "watchers": 0
        },
        "name": "docs-tigrbl-com",
        "route": "/catalog/repositories/tigrbl/docs-tigrbl-com"
      },
      {
        "description": "ZDX and MkDocs Material documentation website for docs.tigrcorn.com.",
        "id": "repository:tigrbl/docs-tigrcorn-com",
        "metrics": {
          "commits": 34,
          "contributors": 1,
          "deployments": 0,
          "environments": 1,
          "forks": 0,
          "github_releases": 0,
          "open_issues": 0,
          "packages": 2,
          "related_resources": 4,
          "size_kb": 130,
          "stars": 0,
          "watchers": 0
        },
        "name": "docs-tigrcorn-com",
        "route": "/catalog/repositories/tigrbl/docs-tigrcorn-com"
      }
    ],
    "forks": 2,
    "github_releases": 1282,
    "id": "organization:tigrbl",
    "kind": "organization",
    "login": "tigrbl",
    "observed_at": "2026-08-03T23:39:08Z",
    "package_count": 584,
    "package_releases": 1835,
    "relationships": 3949,
    "repository_count": 15,
    "role": "ecosystem",
    "route": "/products/tigrbl",
    "stars": 9,
    "technologies": [
      "CSS",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Jupyter Notebook",
      "Makefile",
      "Python",
      "Rust",
      "Shell",
      "TypeScript"
    ],
    "watchers": 1
  }
] as const;

export const catalogFeaturedRepositories = [
  {
    "description": "Modular Python SDK and monorepo for AI agents, LLM integrations, tools, parsers, embeddings, vector stores, and extensible application workflows.",
    "display_name": "swarmauri-sdk",
    "id": "repository:swarmauri/swarmauri-sdk",
    "metrics": {
      "commits": 17469,
      "contributors": 20,
      "deployments": 802,
      "environments": 91,
      "forks": 51,
      "github_releases": 5742,
      "open_issues": 176,
      "packages": 366,
      "related_resources": 111,
      "size_kb": 77235,
      "stars": 104,
      "watchers": 5
    },
    "observed_at": "2026-08-03T22:06:02Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/swarmauri-sdk",
    "technologies": [
      "C",
      "C++",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Jinja",
      "Meson",
      "Python",
      "Rust",
      "Shell"
    ]
  },
  {
    "description": "A UI Component Library by Swarmauri",
    "display_name": "swarmakit",
    "id": "repository:swarmauri/swarmakit",
    "metrics": {
      "commits": 736,
      "contributors": 6,
      "deployments": 2,
      "environments": 1,
      "forks": 10,
      "github_releases": 3,
      "open_issues": 9,
      "packages": 5,
      "related_resources": 1,
      "size_kb": 3968,
      "stars": 25,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:44Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/swarmakit",
    "technologies": [
      "CSS",
      "HTML",
      "JavaScript",
      "MDX",
      "Svelte",
      "TypeScript",
      "Vue"
    ]
  },
  {
    "description": "Public source repository swarmauri/swarmauri-notebooks.",
    "display_name": "swarmauri-notebooks",
    "id": "repository:swarmauri/swarmauri-notebooks",
    "metrics": {
      "commits": 378,
      "contributors": 20,
      "deployments": 0,
      "environments": 0,
      "forks": 31,
      "github_releases": 1,
      "open_issues": 25,
      "packages": 0,
      "related_resources": 1,
      "size_kb": 32789,
      "stars": 18,
      "watchers": 4
    },
    "observed_at": "2026-08-03T23:39:49Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/swarmauri-notebooks",
    "technologies": [
      "Jupyter Notebook"
    ]
  },
  {
    "description": "A CRUD Router for Fast-Creation of CRUD Routes",
    "display_name": "crouton",
    "id": "repository:swarmauri/crouton",
    "metrics": {
      "commits": 208,
      "contributors": 6,
      "deployments": 0,
      "environments": 0,
      "forks": 6,
      "github_releases": 0,
      "open_issues": 8,
      "packages": 2,
      "related_resources": 1,
      "size_kb": 237,
      "stars": 10,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:36Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/crouton",
    "technologies": [
      "Python"
    ]
  },
  {
    "description": "A multi-provider, multi-model retrieval augmentation chatbot.",
    "display_name": "rag_assistant",
    "id": "repository:swarmauri/rag_assistant",
    "metrics": {
      "commits": 133,
      "contributors": 2,
      "deployments": 0,
      "environments": 0,
      "forks": 2,
      "github_releases": 1,
      "open_issues": 2,
      "packages": 1,
      "related_resources": 1,
      "size_kb": 254,
      "stars": 7,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:42Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/rag_assistant",
    "technologies": [
      "Python"
    ]
  },
  {
    "description": "Repository-agnostic Python CLI for single-source-of-truth traceability from features to evidence-backed releases.",
    "display_name": "ssot-registry",
    "id": "repository:groupsum/ssot-registry",
    "metrics": {
      "commits": 485,
      "contributors": 2,
      "deployments": 528,
      "environments": 1,
      "forks": 0,
      "github_releases": 447,
      "open_issues": 0,
      "packages": 14,
      "related_resources": 35,
      "size_kb": 77017,
      "stars": 5,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:24Z",
    "owner": "groupsum",
    "route": "/catalog/repositories/groupsum/ssot-registry",
    "technologies": [
      "CSS",
      "HTML",
      "JavaScript",
      "Makefile",
      "Python",
      "Rust",
      "Shell",
      "TypeScript"
    ]
  },
  {
    "description": "An LLM playground by Swarmauri",
    "display_name": "swarmauri-playground",
    "id": "repository:swarmauri/swarmauri-playground",
    "metrics": {
      "commits": 37,
      "contributors": 4,
      "deployments": 0,
      "environments": 0,
      "forks": 4,
      "github_releases": 0,
      "open_issues": 9,
      "packages": 0,
      "related_resources": 1,
      "size_kb": 34,
      "stars": 5,
      "watchers": 1
    },
    "observed_at": "2026-08-03T23:39:53Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/swarmauri-playground",
    "technologies": [
      "Jupyter Notebook",
      "Python"
    ]
  },
  {
    "description": "MdWrk is a local-first Markdown workspace, preview editor, package platform, and extension host for portable Markdown authoring.",
    "display_name": "markdown_workspace",
    "id": "repository:groupsum/markdown_workspace",
    "metrics": {
      "commits": 837,
      "contributors": 2,
      "deployments": 0,
      "environments": 0,
      "forks": 1,
      "github_releases": 6,
      "open_issues": 0,
      "packages": 45,
      "related_resources": 76,
      "size_kb": 1133214,
      "stars": 3,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:17Z",
    "owner": "groupsum",
    "route": "/catalog/repositories/groupsum/markdown_workspace",
    "technologies": [
      "CSS",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Python",
      "Shell",
      "TypeScript",
      "XSLT"
    ]
  },
  {
    "description": "Schema-first Python and Rust workspace for REST and JSON-RPC APIs with typed validation, SQLAlchemy models, and engine-backed execution.",
    "display_name": "tigrbl",
    "id": "repository:tigrbl/tigrbl",
    "metrics": {
      "commits": 638,
      "contributors": 2,
      "deployments": 0,
      "environments": 0,
      "forks": 0,
      "github_releases": 1202,
      "open_issues": 2,
      "packages": 54,
      "related_resources": 31,
      "size_kb": 73673,
      "stars": 3,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:30Z",
    "owner": "tigrbl",
    "route": "/catalog/repositories/tigrbl/tigrbl",
    "technologies": [
      "Jupyter Notebook",
      "Python"
    ]
  },
  {
    "description": "ASGI3 server with built-in HTTP/1.1, HTTP/2, HTTP/3, QUIC, WebSocket, TLS, static delivery, and release validation.",
    "display_name": "tigrcorn",
    "id": "repository:tigrbl/tigrcorn",
    "metrics": {
      "commits": 274,
      "contributors": 4,
      "deployments": 2454,
      "environments": 6,
      "forks": 2,
      "github_releases": 40,
      "open_issues": 15,
      "packages": 16,
      "related_resources": 37,
      "size_kb": 18970,
      "stars": 3,
      "watchers": 1
    },
    "observed_at": "2026-08-03T23:39:36Z",
    "owner": "tigrbl",
    "route": "/catalog/repositories/tigrbl/tigrcorn",
    "technologies": [
      "HTML",
      "Makefile",
      "Python",
      "Shell",
      "TypeScript"
    ]
  },
  {
    "description": "Swarmauri custom mesop components",
    "display_name": "swarmauri-mesop-components",
    "id": "repository:swarmauri/swarmauri-mesop-components",
    "metrics": {
      "commits": 11,
      "contributors": 2,
      "deployments": 0,
      "environments": 0,
      "forks": 1,
      "github_releases": 0,
      "open_issues": 0,
      "packages": 0,
      "related_resources": 1,
      "size_kb": 17,
      "stars": 3,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:48Z",
    "owner": "swarmauri",
    "route": "/catalog/repositories/swarmauri/swarmauri-mesop-components",
    "technologies": [
      "JavaScript",
      "Python"
    ]
  },
  {
    "description": "Tigrbl-native multi-tenant OpenID Connect / OAuth 2.0 identity provider with ASGI runtime profiles, JWKS/JWT support, operator controls, and SSOT-backed compliance evidence.",
    "display_name": "tigrbl_auth",
    "id": "repository:tigrbl/tigrbl_auth",
    "metrics": {
      "commits": 916,
      "contributors": 2,
      "deployments": 121,
      "environments": 1,
      "forks": 0,
      "github_releases": 12,
      "open_issues": 13,
      "packages": 489,
      "related_resources": 56,
      "size_kb": 25828,
      "stars": 2,
      "watchers": 0
    },
    "observed_at": "2026-08-03T23:39:33Z",
    "owner": "tigrbl",
    "route": "/catalog/repositories/tigrbl/tigrbl_auth",
    "technologies": [
      "CSS",
      "Dockerfile",
      "HTML",
      "JavaScript",
      "Python",
      "Shell",
      "TypeScript"
    ]
  }
] as const;

export const catalogTechnologies = [
  {
    "bytes": 32697478,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:python:18885f27",
    "kind": "technology",
    "name": "Python",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/ad-measurement-media-governance-pack",
      "groupsum/ad-supply-chain-transparency-governance-pack",
      "groupsum/audience-data-transparency-governance-pack",
      "groupsum/authentication-governance-pack",
      "groupsum/authnz-policy-governance-pack",
      "groupsum/authorization-policy-governance-pack",
      "groupsum/cache-freshness-governance-pack",
      "groupsum/consent-privacy-signals-governance-pack",
      "groupsum/customer-commerce-semantics-governance-pack",
      "groupsum/customer-identity-profile-governance-pack",
      "groupsum/data-catalog-lineage-contracts-governance-pack",
      "groupsum/decentralized-identifiers-governance-pack",
      "groupsum/digital-signature-governance-pack",
      "groupsum/event-behavioral-telemetry-governance-pack",
      "groupsum/ga4-google-tagging-governance-pack",
      "groupsum/groupsum-xyz",
      "groupsum/gs1-product-link-event-data-governance-pack",
      "groupsum/markdown_workspace",
      "groupsum/marketing-attribution-conversion-governance-pack",
      "groupsum/mdwrk",
      "groupsum/mdwrk-pages",
      "groupsum/mobile-install-attribution-governance-pack",
      "groupsum/npmctl",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/privacy-governance-records-governance-pack",
      "groupsum/seo-aeo-aieo-governance-pack",
      "groupsum/ssot-registry",
      "groupsum/ssot-registry-com",
      "groupsum/url-query-attribution-foundations-governance-pack",
      "groupsum/verifiable-credentials-governance-pack",
      "groupsum/web-app-analytics-governance-pack",
      "groupsum/web-performance-rum-governance-pack",
      "swarmauri/crouton",
      "swarmauri/crouton-boilerplate",
      "swarmauri/docs-peagen-com",
      "swarmauri/docs-swarmauri-com",
      "swarmauri/peagen-com",
      "swarmauri/rag_assistant",
      "swarmauri/soliloquy",
      "swarmauri/swarmauri-aucplot",
      "swarmauri/swarmauri-com",
      "swarmauri/swarmauri-mesop-components",
      "swarmauri/swarmauri-piechart",
      "swarmauri/swarmauri-playground",
      "swarmauri/swarmauri-sdk",
      "tigrbl/attribution-campaign-context",
      "tigrbl/docs-tigrbl-com",
      "tigrbl/docs-tigrcorn-com",
      "tigrbl/tigr-asgi-contract",
      "tigrbl/tigrbl",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_acme_ca",
      "tigrbl/tigrbl_api_cron",
      "tigrbl/tigrbl_api_hpks",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrbl_billing",
      "tigrbl/tigrbl_kms",
      "tigrbl/tigrbl_spiffe",
      "tigrbl/tigrcorn",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 61,
    "route": "/catalog/technologies/python-18885f27"
  },
  {
    "bytes": 4193027,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:javascript:b27ad06d",
    "kind": "technology",
    "name": "JavaScript",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/groupsum-xyz",
      "groupsum/markdown_workspace",
      "groupsum/mdwrk",
      "groupsum/mdwrk-pages",
      "groupsum/mdwrkcom-content-pack",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/ssot-registry",
      "groupsum/ssot-registry-com",
      "swarmauri/docs-peagen-com",
      "swarmauri/docs-swarmauri-com",
      "swarmauri/peagen-com",
      "swarmauri/swarmakit",
      "swarmauri/swarmauri-aucplot",
      "swarmauri/swarmauri-com",
      "swarmauri/swarmauri-flipcard",
      "swarmauri/swarmauri-mesop-components",
      "swarmauri/swarmauri-piechart",
      "swarmauri/swarmauri-sdk",
      "tigrbl/docs-tigrbl-com",
      "tigrbl/docs-tigrcorn-com",
      "tigrbl/tigr-asgi-contract",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 25,
    "route": "/catalog/technologies/javascript-b27ad06d"
  },
  {
    "bytes": 47408631,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:typescript:ed0504f7",
    "kind": "technology",
    "name": "TypeScript",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/document-studio",
      "groupsum/document-viewer",
      "groupsum/file-browser",
      "groupsum/groupsum-xyz",
      "groupsum/markdown_workspace",
      "groupsum/mdwrk",
      "groupsum/mdwrk-pages",
      "groupsum/mdwrkcom-content-pack",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/ssot-registry",
      "groupsum/ssot-registry-com",
      "swarmauri/peagen-com",
      "swarmauri/swarmakit",
      "swarmauri/swarmauri-com",
      "tigrbl/tigr-asgi-contract",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrcorn",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 20,
    "route": "/catalog/technologies/typescript-ed0504f7"
  },
  {
    "bytes": 21207871,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:html:07239dbd",
    "kind": "technology",
    "name": "HTML",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/document-studio",
      "groupsum/document-viewer",
      "groupsum/file-browser",
      "groupsum/groupsum-xyz",
      "groupsum/markdown_workspace",
      "groupsum/mdwrk",
      "groupsum/mdwrk-pages",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/ssot-registry",
      "groupsum/ssot-registry-com",
      "swarmauri/peagen-com",
      "swarmauri/swarmakit",
      "swarmauri/swarmauri-com",
      "swarmauri/swarmauri-flipcard",
      "swarmauri/swarmauri-sdk",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrcorn",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 20,
    "route": "/catalog/technologies/html-07239dbd"
  },
  {
    "bytes": 10359524,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:css:b581e460",
    "kind": "technology",
    "name": "CSS",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/document-studio",
      "groupsum/document-viewer",
      "groupsum/file-browser",
      "groupsum/groupsum-xyz",
      "groupsum/markdown_workspace",
      "groupsum/mdwrk",
      "groupsum/mdwrk-pages",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/ssot-registry",
      "groupsum/ssot-registry-com",
      "swarmauri/peagen-com",
      "swarmauri/swarmakit",
      "swarmauri/swarmauri-com",
      "swarmauri/swarmauri-flipcard",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 18,
    "route": "/catalog/technologies/css-b581e460"
  },
  {
    "bytes": 12111,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:dockerfile:dd2c0eb6",
    "kind": "technology",
    "name": "Dockerfile",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/groupsum-xyz",
      "groupsum/markdown_workspace",
      "groupsum/mdwrk-pages",
      "groupsum/npmctl",
      "groupsum/npmctl-com",
      "groupsum/portwyrm",
      "groupsum/ssot-registry-com",
      "swarmauri/docs-peagen-com",
      "swarmauri/docs-swarmauri-com",
      "swarmauri/peagen-com",
      "swarmauri/swarmauri-com",
      "swarmauri/swarmauri-sdk",
      "tigrbl/docs-tigrbl-com",
      "tigrbl/docs-tigrcorn-com",
      "tigrbl/tigrbl-com",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrbl_kms",
      "tigrbl/tigrcorn-com"
    ],
    "repository_count": 18,
    "route": "/catalog/technologies/dockerfile-dd2c0eb6"
  },
  {
    "bytes": 13817,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:shell:a7332854",
    "kind": "technology",
    "name": "Shell",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/markdown_workspace",
      "groupsum/mdwrk",
      "groupsum/npmctl",
      "groupsum/ssot-registry",
      "swarmauri/swarmauri-sdk",
      "tigrbl/tigrbl_auth",
      "tigrbl/tigrcorn"
    ],
    "repository_count": 7,
    "route": "/catalog/technologies/shell-a7332854"
  },
  {
    "bytes": 147053,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:svelte:0073bfca",
    "kind": "technology",
    "name": "Svelte",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmakit",
      "swarmauri/swarmauri-aucplot",
      "swarmauri/swarmauri-flipcard",
      "swarmauri/swarmauri-piechart"
    ],
    "repository_count": 4,
    "route": "/catalog/technologies/svelte-0073bfca"
  },
  {
    "bytes": 25381,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:xslt:1370c71d",
    "kind": "technology",
    "name": "XSLT",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/markdown_workspace",
      "groupsum/mdwrkcom-content-pack",
      "groupsum/ssot-registry-com",
      "swarmauri/swarmauri-com"
    ],
    "repository_count": 4,
    "route": "/catalog/technologies/xslt-1370c71d"
  },
  {
    "bytes": 40169540,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:jupyter-notebook:c98b6019",
    "kind": "technology",
    "name": "Jupyter Notebook",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmauri-notebooks",
      "swarmauri/swarmauri-playground",
      "tigrbl/tigrbl"
    ],
    "repository_count": 3,
    "route": "/catalog/technologies/jupyter-notebook-c98b6019"
  },
  {
    "bytes": 61394,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:rust:d9aa89fd",
    "kind": "technology",
    "name": "Rust",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/ssot-registry",
      "swarmauri/swarmauri-sdk",
      "tigrbl/tigr-asgi-contract"
    ],
    "repository_count": 3,
    "route": "/catalog/technologies/rust-d9aa89fd"
  },
  {
    "bytes": 181157,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:makefile:76ed074a",
    "kind": "technology",
    "name": "Makefile",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "groupsum/ssot-registry",
      "tigrbl/tigrcorn"
    ],
    "repository_count": 2,
    "route": "/catalog/technologies/makefile-76ed074a"
  },
  {
    "bytes": 298691,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:vue:b111a2a2",
    "kind": "technology",
    "name": "Vue",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmakit"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/vue-b111a2a2"
  },
  {
    "bytes": 32243,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:c:f1deb75f",
    "kind": "technology",
    "name": "C++",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmauri-sdk"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/c-f1deb75f"
  },
  {
    "bytes": 18019,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:jinja:7c43eabf",
    "kind": "technology",
    "name": "Jinja",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmauri-sdk"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/jinja-7c43eabf"
  },
  {
    "bytes": 11360,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:mdx:d434e4eb",
    "kind": "technology",
    "name": "MDX",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmakit"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/mdx-d434e4eb"
  },
  {
    "bytes": 4296,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:meson:33742f46",
    "kind": "technology",
    "name": "Meson",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmauri-sdk"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/meson-33742f46"
  },
  {
    "bytes": 4211,
    "evidence": [
      {
        "kind": "github-languages",
        "observed_at": "2026-08-03T23:39:08Z"
      }
    ],
    "id": "technology:c:6b23c0d5",
    "kind": "technology",
    "name": "C",
    "observed_at": "2026-08-03T23:39:08Z",
    "repositories": [
      "swarmauri/swarmauri-sdk"
    ],
    "repository_count": 1,
    "route": "/catalog/technologies/c-6b23c0d5"
  }
] as const;

export const catalogDatasetManifest = {
  "completeness": {
    "commits": "all default-branch commits returned by GitHub REST pagination",
    "contributors": "all contributors returned by GitHub REST, including anonymous rows",
    "deployments": "GitHub deployment records attached to repositories; live health is not implied",
    "downstream": "crates.io reverse dependencies where available; GitHub code search disabled by default; npm and PyPI have no complete authoritative public dependents API",
    "github_releases": "all releases returned by GitHub REST",
    "packages": "manifest-discovered packages plus public GitHub packages returned by API",
    "registries": "direct PyPI, npm, crates.io, GitHub Releases, and GitHub Packages observations",
    "related_resources": "repository homepages and source paths for APIs, demos, documentation, examples, showcases, UIs, and websites; reachability is not implied",
    "repositories": "all public repositories returned by configured GitHub organization APIs after configured name, archive, and fork exclusions",
    "technologies": "GitHub language byte counts; no technology is inferred from marketing copy"
  },
  "counts": {
    "organizations": 4,
    "packages": 1125,
    "repositories": 68,
    "resources": 575,
    "technologies": 18
  },
  "files": [
    {
      "bytes": 19733,
      "dataset": "organizations",
      "path": "organizations.json",
      "records": 4,
      "sha256": "b1b4957d094d6257a21ed2e7394c7f8f320678f6ce71c8c03942c63daa1f8746"
    },
    {
      "bytes": 13490923,
      "dataset": "packages",
      "path": "packages.json",
      "records": 1125,
      "sha256": "832ed1925244637aaeebe55dfc7374bab126d6cc0f16d65522bfcedbee8baa07"
    },
    {
      "bytes": 22455148,
      "dataset": "repositories",
      "path": "repositories.json",
      "records": 68,
      "sha256": "b79098f841a778526d1f166d98f2e34cf3313c0ce6d5536921257336f367bb7e"
    },
    {
      "bytes": 706963,
      "dataset": "resources",
      "path": "resources.json",
      "records": 575,
      "sha256": "fbbd0feb77ece8fa3b89a2a8af8845858cbb3c46ecc5f8db8842b7d5120f3b27"
    },
    {
      "bytes": 13753,
      "dataset": "technologies",
      "path": "technologies.json",
      "records": 18,
      "sha256": "94b84041af84a67473f7fe6b57a1598990ea0d42e265aa28ca7b9a71159967d2"
    }
  ],
  "generated_at": "2026-08-03T23:39:08Z",
  "product_evidence": {
    "path": "/catalog/product-evidence/",
    "records": 69
  },
  "schema_version": "1.0.0",
  "source": "/catalog/catalog.json",
  "source_counts": {
    "deployments": 4010,
    "relationships": 10734,
    "releases": 17313
  }
} as const;
